export const GET_SYLLABUS = "GET_SYLLABUS";
export const BLOCK_UNBLOCK_SYLLABUS = "BLOCK_UNBLOCK_SYLLABUS";
export const CREATE_NEW_SYLLABUS = "CREATE_NEW_SYLLABUS";
export const SET_CREATE_SYLLABUS_DONE = "SET_CREATE_SYLLABUS_DONE";
export const UNSET_CREATE_SYLLABUS_DONE = "UNSET_CREATE_SYLLABUS_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_SYLLABUS_DIALOG = "OPEN_SYLLABUS_DIALOG";
export const CLOSE_SYLLABUS_DIALOG = "CLOSE_SYLLABUS_DIALOG";
export const EDIT_SYLLABUS = "EDIT_SYLLABUS";
export const SET_UPDATE_SYLLABUS_DONE = "SET_UPDATE_SYLLABUS_DONE";
export const UNSET_UPDATE_SYLLABUS_DONE = "UNSET_UPDATE_SYLLABUS_DONE";
export const TEST_DELETE_SYLLABUS_DONE = "TEST_DELETE_SYLLABUS_DONE";
export const UNSET_TEST_DELETE_SYLLABUS_DONE = "UNSET_TEST_DELETE_SYLLABUS_DONE";

