export const GET_FAQ = "GET_FAQ";
export const BLOCK_UNBLOCK_FAQ = "BLOCK_UNBLOCK_FAQ";
export const CREATE_NEW_FAQ = "CREATE_NEW_FAQ";
export const SET_CREATE_FAQ_DONE = "SET_CREATE_FAQ_DONE";
export const UNSET_CREATE_FAQ_DONE = "UNSET_CREATE_FAQ_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_FAQ_DIALOG = "OPEN_FAQ_DIALOG";
export const CLOSE_FAQ_DIALOG = "CLOSE_FAQ_DIALOG";
export const EDIT_FAQ = "EDIT_FAQ";
export const SET_UPDATE_FAQ_DONE = "SET_UPDATE_FAQ_DONE";
export const UNSET_UPDATE_FAQ_DONE = "UNSET_UPDATE_FAQ_DONE";
export const TEST_DELETE_FAQ_DONE = "TEST_DELETE_FAQ_DONE";
export const UNSET_TEST_DELETE_FAQ_DONE = "UNSET_TEST_DELETE_FAQ_DONE";

