export const GET_WHATCLIENTSAY = "GET_WHATCLIENTSAY";
export const BLOCK_UNBLOCK_WHATCLIENTSAY = "BLOCK_UNBLOCK_WHATCLIENTSAY";
export const CREATE_NEW_WHATCLIENTSAY = "CREATE_NEW_WHATCLIENTSAY";
export const SET_CREATE_WHATCLIENTSAY_DONE = "SET_CREATE_WHATCLIENTSAY_DONE";
export const UNSET_CREATE_WHATCLIENTSAY_DONE = "UNSET_CREATE_WHATCLIENTSAY_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_WHATCLIENTSAY_DIALOG = "OPEN_WHATCLIENTSAY_DIALOG";
export const CLOSE_WHATCLIENTSAY_DIALOG = "CLOSE_WHATCLIENTSAY_DIALOG";
export const EDIT_WHATCLIENTSAY = "EDIT_WHATCLIENTSAY";
export const SET_UPDATE_WHATCLIENTSAY_DONE = "SET_UPDATE_WHATCLIENTSAY_DONE";
export const UNSET_UPDATE_WHATCLIENTSAY_DONE = "UNSET_UPDATE_WHATCLIENTSAY_DONE";
export const TEST_DELETE_WHATCLIENTSAY_DONE = "TEST_DELETE_WHATCLIENTSAY_DONE";
export const UNSET_TEST_DELETE_WHATCLIENTSAY_DONE = "UNSET_TEST_DELETE_WHATCLIENTSAY_DONE";

