export const GET_NOTES = "GET_NOTES";
export const BLOCK_UNBLOCK_NOTES = "BLOCK_UNBLOCK_NOTES";
export const CREATE_NEW_NOTES = "CREATE_NEW_NOTES";
export const SET_CREATE_NOTES_DONE = "SET_CREATE_NOTES_DONE";
export const UNSET_CREATE_NOTES_DONE = "UNSET_CREATE_NOTES_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_NOTES_DIALOG = "OPEN_NOTES_DIALOG";
export const CLOSE_NOTES_DIALOG = "CLOSE_NOTES_DIALOG";
export const EDIT_NOTES = "EDIT_NOTES";
export const SET_UPDATE_NOTES_DONE = "SET_UPDATE_NOTES_DONE";
export const UNSET_UPDATE_NOTES_DONE = "UNSET_UPDATE_NOTES_DONE";
export const TEST_DELETE_NOTES_DONE = "TEST_DELETE_NOTES_DONE";
export const UNSET_TEST_DELETE_NOTES_DONE = "UNSET_TEST_DELETE_NOTES_DONE";

