export const GET_SEM = "GET_SEM";
export const BLOCK_UNBLOCK_SEM = "BLOCK_UNBLOCK_SEM";
export const CREATE_NEW_SEM = "CREATE_NEW_SEM";
export const SET_CREATE_SEM_DONE = "SET_CREATE_SEM_DONE";
export const UNSET_CREATE_SEM_DONE = "UNSET_CREATE_SEM_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_SEM_DIALOG = "OPEN_SEM_DIALOG";
export const CLOSE_SEM_DIALOG = "CLOSE_SEM_DIALOG";
export const EDIT_SEM = "EDIT_SEM";
export const SET_UPDATE_SEM_DONE = "SET_UPDATE_SEM_DONE";
export const UNSET_UPDATE_SEM_DONE = "UNSET_UPDATE_SEM_DONE";
export const TEST_DELETE_SEM_DONE = "TEST_DELETE_SEM_DONE";
export const UNSET_TEST_DELETE_SEM_DONE = "UNSET_TEST_DELETE_SEM_DONE";

export const GET_SEM_BY_COURSE_ID = "GET_SEM_BY_COURSE_ID";

export const ERROR ="ERROR";