export const GET_PRACTICAL = "GET_PRACTICAL";
export const BLOCK_UNBLOCK_PRACTICAL = "BLOCK_UNBLOCK_PRACTICAL";
export const CREATE_NEW_PRACTICAL = "CREATE_NEW_PRACTICAL";
export const SET_CREATE_PRACTICAL_DONE = "SET_CREATE_PRACTICAL_DONE";
export const UNSET_CREATE_PRACTICAL_DONE = "UNSET_CREATE_PRACTICAL_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_PRACTICAL_DIALOG = "OPEN_PRACTICAL_DIALOG";
export const CLOSE_PRACTICAL_DIALOG = "CLOSE_PRACTICAL_DIALOG";
export const EDIT_PRACTICAL = "EDIT_PRACTICAL";
export const SET_UPDATE_PRACTICAL_DONE = "SET_UPDATE_PRACTICAL_DONE";
export const UNSET_UPDATE_PRACTICAL_DONE = "UNSET_UPDATE_PRACTICAL_DONE";
export const TEST_DELETE_PRACTICAL_DONE = "TEST_DELETE_PRACTICAL_DONE";
export const UNSET_TEST_DELETE_PRACTICAL_DONE = "UNSET_TEST_DELETE_PRACTICAL_DONE";

