export const GET_MISSION = "GET_MISSION";
export const BLOCK_UNBLOCK_MISSION = "BLOCK_UNBLOCK_MISSION";
export const CREATE_NEW_MISSION = "CREATE_NEW_MISSION";
export const SET_CREATE_MISSION_DONE = "SET_CREATE_MISSION_DONE";
export const UNSET_CREATE_MISSION_DONE = "UNSET_CREATE_MISSION_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_MISSION_DIALOG = "OPEN_MISSION_DIALOG";
export const CLOSE_MISSION_DIALOG = "CLOSE_MISSION_DIALOG";
export const EDIT_MISSION = "EDIT_MISSION";
export const SET_UPDATE_MISSION_DONE = "SET_UPDATE_MISSION_DONE";
export const UNSET_UPDATE_MISSION_DONE = "UNSET_UPDATE_MISSION_DONE";
export const TEST_DELETE_MISSION_DONE = "TEST_DELETE_MISSION_DONE";
export const UNSET_TEST_DELETE_MISSION_DONE = "UNSET_TEST_DELETE_MISSION_DONE";

