export const GET_QUESTIONMODAL = "GET_QUESTIONMODAL";
export const BLOCK_UNBLOCK_QUESTIONMODAL = "BLOCK_UNBLOCK_QUESTIONMODAL";
export const CREATE_NEW_QUESTIONMODAL = "CREATE_NEW_QUESTIONMODAL";
export const SET_CREATE_QUESTIONMODAL_DONE = "SET_CREATE_QUESTIONMODAL_DONE";
export const UNSET_CREATE_QUESTIONMODAL_DONE = "UNSET_CREATE_QUESTIONMODAL_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_QUESTIONMODAL_DIALOG = "OPEN_QUESTIONMODAL_DIALOG";
export const CLOSE_QUESTIONMODAL_DIALOG = "CLOSE_QUESTIONMODAL_DIALOG";
export const EDIT_QUESTIONMODAL = "EDIT_QUESTIONMODAL";
export const SET_UPDATE_QUESTIONMODAL_DONE = "SET_UPDATE_QUESTIONMODAL_DONE";
export const UNSET_UPDATE_QUESTIONMODAL_DONE = "UNSET_UPDATE_QUESTIONMODAL_DONE";
export const TEST_DELETE_QUESTIONMODAL_DONE = "TEST_DELETE_QUESTIONMODAL_DONE";
export const UNSET_TEST_DELETE_QUESTIONMODAL_DONE = "UNSET_TEST_DELETE_QUESTIONMODAL_DONE";

