export const ALL_BLOG = "ALL_BLOG";
export const ADD_FAKEHOST = "ADD_FAKEHOST";
export const UPDATE_FAKEHOST = "UPDATE_FAKEHOST";
export const CLOSE_BLOG_DIALOG = "CLOSE_BLOG_DIALOG";
export const OPEN_BLOG_DIALOG = "OPEN_BLOG_DIALOG";
export const CREATE_NEW_BLOG = "CREATE_NEW_BLOG"
export const SET_CREATE_AGENCY_DONE = "SET_CREATE_AGENCY_DONE";
export const UNSET_CREATE_AGENCY_DONE = "UNSET_CREATE_AGENCY_DONE";
export const SET_UPDATE_AGENCY_DONE = "SET_UPDATE_AGENCY_DONE";
export const UNSET_UPDATE_AGENCY_DONE = "UNSET_UPDATE_AGENCY_DONE";
export const EDIT_BLOG = "EDIT_BLOG";
export const IS_ONLINE_BLOG = "IS_ONLINE_BLOG"
export const BLOCK_UNBLOCK_BLOG ="BLOCK_UNBLOCK_BLOG"

export const BLOG_DELETE_DONE = "BLOG_DELETE_DONE";
export const UNSET_BLOG_DELETE_DONE = "UNSET_BLOG_DELETE_DONE";

