export const GET_SUBJECT = "GET_SUBJECT";
export const BLOCK_UNBLOCK_SUBJECT = "BLOCK_UNBLOCK_SUBJECT";
export const CREATE_NEW_SUBJECT = "CREATE_NEW_SUBJECT";
export const SET_CREATE_SUBJECT_DONE = "SET_CREATE_SUBJECT_DONE";
export const UNSET_CREATE_SUBJECT_DONE = "UNSET_CREATE_SUBJECT_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_SUBJECT_DIALOG = "OPEN_SUBJECT_DIALOG";
export const CLOSE_SUBJECT_DIALOG = "CLOSE_SUBJECT_DIALOG";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const SET_UPDATE_SUBJECT_DONE = "SET_UPDATE_SUBJECT_DONE";
export const UNSET_UPDATE_SUBJECT_DONE = "UNSET_UPDATE_SUBJECT_DONE";
export const TEST_DELETE_SUBJECT_DONE = "TEST_DELETE_SUBJECT_DONE";
export const UNSET_TEST_DELETE_SUBJECT_DONE = "UNSET_TEST_DELETE_SUBJECT_DONE";

export const GET_SUBJECT_BY_COURSE_ID_SEM_ID ="GET_SUBJECT_BY_COURSE_ID_SEM_ID";
