export const GET_COURSE = "GET_COURSE";
export const BLOCK_UNBLOCK_COURSE = "BLOCK_UNBLOCK_COURSE";
export const CREATE_NEW_COURSE = "CREATE_NEW_COURSE";
export const SET_CREATE_COURSE_DONE = "SET_CREATE_COURSE_DONE";
export const UNSET_CREATE_COURSE_DONE = "UNSET_CREATE_COURSE_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_COURSE_DIALOG = "OPEN_COURSE_DIALOG";
export const CLOSE_COURSE_DIALOG = "CLOSE_COURSE_DIALOG";
export const EDIT_COURSE = "EDIT_COURSE";
export const SET_UPDATE_COURSE_DONE = "SET_UPDATE_COURSE_DONE";
export const UNSET_UPDATE_COURSE_DONE = "UNSET_UPDATE_COURSE_DONE";
export const TEST_DELETE_COURSE_DONE = "TEST_DELETE_COURSE_DONE";
export const UNSET_TEST_DELETE_COURSE_DONE = "UNSET_TEST_DELETE_COURSE_DONE";

