export const GET_TEST = "GET_TEST";
export const BLOCK_UNBLOCK_TEST = "BLOCK_UNBLOCK_TEST";
export const CREATE_NEW_TEST = "CREATE_NEW_TEST";
export const SET_CREATE_TEST_DONE = "SET_CREATE_TEST_DONE";
export const UNSET_CREATE_TEST_DONE = "UNSET_CREATE_TEST_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_TEST_DIALOG = "OPEN_TEST_DIALOG";
export const CLOSE_TEST_DIALOG = "CLOSE_TEST_DIALOG";
export const EDIT_TEST = "EDIT_TEST";
export const SET_UPDATE_TEST_DONE = "SET_UPDATE_TEST_DONE";
export const UNSET_UPDATE_TEST_DONE = "UNSET_UPDATE_TEST_DONE";
export const TEST_DELETE_TEST_DONE = "TEST_DELETE_TEST_DONE";
export const UNSET_TEST_DELETE_TEST_DONE = "UNSET_TEST_DELETE_TEST_DONE";

