export const GET_NOTESUNIT = "GET_NOTESUNIT";
export const BLOCK_UNBLOCK_NOTESUNIT = "BLOCK_UNBLOCK_NOTESUNIT";
export const CREATE_NEW_NOTESUNIT = "CREATE_NEW_NOTESUNIT";
export const SET_CREATE_NOTESUNIT_DONE = "SET_CREATE_NOTESUNIT_DONE";
export const UNSET_CREATE_NOTESUNIT_DONE = "UNSET_CREATE_NOTESUNIT_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_NOTESUNIT_DIALOG = "OPEN_NOTESUNIT_DIALOG";
export const CLOSE_NOTESUNIT_DIALOG = "CLOSE_NOTESUNIT_DIALOG";
export const EDIT_NOTESUNIT = "EDIT_NOTESUNIT";
export const SET_UPDATE_NOTESUNIT_DONE = "SET_UPDATE_NOTESUNIT_DONE";
export const UNSET_UPDATE_NOTESUNIT_DONE = "UNSET_UPDATE_NOTESUNIT_DONE";
export const TEST_DELETE_NOTESUNIT_DONE = "TEST_DELETE_NOTESUNIT_DONE";
export const UNSET_TEST_DELETE_NOTESUNIT_DONE = "UNSET_TEST_DELETE_NOTESUNIT_DONE";

