export const GET_BOOK = "GET_BOOK";
export const BLOCK_UNBLOCK_BOOK = "BLOCK_UNBLOCK_BOOK";
export const CREATE_NEW_BOOK = "CREATE_NEW_BOOK";
export const SET_CREATE_BOOK_DONE = "SET_CREATE_BOOK_DONE";
export const UNSET_CREATE_BOOK_DONE = "UNSET_CREATE_BOOK_DONE";

export const TEST_DELETE_CATEGORY_DONE = "TEST_DELETE_CATEGORY_DONE";
export const UNSET_TEST_DELETE_CATEGORY_DONE =
  "UNSET_TEST_DELETE_CATEGORY_DONE";
  
export const OPEN_BOOK_DIALOG = "OPEN_BOOK_DIALOG";
export const CLOSE_BOOK_DIALOG = "CLOSE_BOOK_DIALOG";
export const EDIT_BOOK = "EDIT_BOOK";
export const SET_UPDATE_BOOK_DONE = "SET_UPDATE_BOOK_DONE";
export const UNSET_UPDATE_BOOK_DONE = "UNSET_UPDATE_BOOK_DONE";
export const TEST_DELETE_BOOK_DONE = "TEST_DELETE_BOOK_DONE";
export const UNSET_TEST_DELETE_BOOK_DONE = "UNSET_TEST_DELETE_BOOK_DONE";

